// WARNING: this file is auto generated, any changes will be lost
import { createDesignComponent, CanvasStore } from "framer"
const canvas = CanvasStore.shared(); // CANVAS_DATA;
export const Filters_Content = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string,$place_name?:string,$place_name?:string,$place_name?:string}>(canvas, "id_ZfPwirxrQ", {$place_name:"string",$place_name:"string",$place_name:"string"}, 375,248);
export const Filters_Item = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string,$place_name?:string}>(canvas, "id_JFQDA0W4e", {$place_name:"string"}, "1fr",60);
export const Icons_BabyChangingTable = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string}>(canvas, "id_YKO4wv8Lg", {}, 18,18);
export const Icons_BabyChangingTable_1 = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string}>(canvas, "id_ZgahXlsG5UILg0l4Z8", {}, 18,18);
export const Icons_Close = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string}>(canvas, "id_xbYTwJutF", {}, 24,24);
export const Icons_GenderNeutral = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string}>(canvas, "id_E58IIvJId", {}, 18,18);
export const Icons_Marker = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string}>(canvas, "id_gCOYvdFqJ", {}, 14,27);
export const Icons_SearchLocation = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string}>(canvas, "id_QVMc8RiG2", {}, 24,24);
export const Icons_WheelchairAccessible = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string}>(canvas, "id_IPs3j7nhK", {}, 18,18);
export const Icons_WheelchairAccessible_1 = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string}>(canvas, "id_ZgahXlsG5gEvGcAqsZ", {}, 18,18);
export const Overlay = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string}>(canvas, "id_Qx3_6MGMS", {}, 375,280);
export const Results_Container = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string,$left?:string}>(canvas, "id_QofOcz2Z3", {$left:"string"}, 375,260);
export const Results_Filters = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string}>(canvas, "id_DEgMY0vq9", {}, 72,18);
export const Results_Header = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string,$left?:string}>(canvas, "id_jm8Uekr7d", {$left:"string"}, 375,50);
export const Results_Item = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string,$placeName?:string}>(canvas, "id_kZwm2U0Oy", {$placeName:"string"}, 371,60);
export const Results_Items = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string,$placeName?:string,$placeName?:string,$placeName?:string,$placeName?:string,$placeName?:string,$placeName?:string,$placeName?:string}>(canvas, "id_iwqokSNtx", {$placeName:"string",$placeName:"string",$placeName:"string",$placeName:"string",$placeName:"string",$placeName:"string",$placeName:"string"}, 375,442);
export const Search_Container = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string,$placeName?:string,$placeName?:string,$placeName?:string,$placeName?:string}>(canvas, "id_yIiwkhorG", {$placeName:"string",$placeName:"string",$placeName:"string",$placeName:"string"}, 375,389);
export const Search_Header = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string}>(canvas, "id_Enuph0vha", {}, 375,100);
export const Search_Item = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string,$placeName?:string}>(canvas, "id_GcEjrjhlm", {$placeName:"string"}, 371,60);
export const Search_Items = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string,$placeName?:string,$placeName?:string,$placeName?:string,$placeName?:string}>(canvas, "id_XhfnnsfPg", {$placeName:"string",$placeName:"string",$placeName:"string",$placeName:"string"}, 375,265);
export const Search_Loading = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string}>(canvas, "id_Uqv7xhcD4", {}, 375,195);
export const Search_SystemHeader = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string}>(canvas, "id_LgcCXOAzr", {}, 375,40);
export const Selected_Content = createDesignComponent<{parentSize?:{width:number|string,height:number|string},width?:number|string,height?:number|string,$placeName?:string,$address?:string,$directions?:string,$comments?:string}>(canvas, "id_aYZJt_4Y1", {$placeName:"string",$address:"string",$directions:"string",$comments:"string"}, 375,348);
