export const cachedBreeds = [
    { breed: "affenpinscher", subBreeds: [] },
    { breed: "african", subBreeds: [] },
    { breed: "airedale", subBreeds: [] },
    { breed: "akita", subBreeds: [] },
    { breed: "appenzeller", subBreeds: [] },
    { breed: "basenji", subBreeds: [] },
    { breed: "beagle", subBreeds: [] },
    { breed: "bluetick", subBreeds: [] },
    { breed: "borzoi", subBreeds: [] },
    { breed: "bouvier", subBreeds: [] },
    { breed: "boxer", subBreeds: [] },
    { breed: "brabancon", subBreeds: [] },
    { breed: "briard", subBreeds: [] },
    {
        breed: "bulldog",
        subBreeds: [
            { breed: "bulldog", subBreed: "boston" },
            { breed: "bulldog", subBreed: "english" },
            { breed: "bulldog", subBreed: "french" },
        ],
    },
    {
        breed: "bullterrier",
        subBreeds: [{ breed: "bullterrier", subBreed: "staffordshire" }],
    },
    { breed: "cairn", subBreeds: [] },
    {
        breed: "cattledog",
        subBreeds: [{ breed: "cattledog", subBreed: "australian" }],
    },
    { breed: "chihuahua", subBreeds: [] },
    { breed: "chow", subBreeds: [] },
    { breed: "clumber", subBreeds: [] },
    { breed: "cockapoo", subBreeds: [] },
    { breed: "collie", subBreeds: [{ breed: "collie", subBreed: "border" }] },
    { breed: "coonhound", subBreeds: [] },
    { breed: "corgi", subBreeds: [{ breed: "corgi", subBreed: "cardigan" }] },
    { breed: "cotondetulear", subBreeds: [] },
    { breed: "dachshund", subBreeds: [] },
    { breed: "dalmatian", subBreeds: [] },
    { breed: "dane", subBreeds: [{ breed: "dane", subBreed: "great" }] },
    {
        breed: "deerhound",
        subBreeds: [{ breed: "deerhound", subBreed: "scottish" }],
    },
    { breed: "dhole", subBreeds: [] },
    { breed: "dingo", subBreeds: [] },
    { breed: "doberman", subBreeds: [] },
    {
        breed: "elkhound",
        subBreeds: [{ breed: "elkhound", subBreed: "norwegian" }],
    },
    { breed: "entlebucher", subBreeds: [] },
    { breed: "eskimo", subBreeds: [] },
    { breed: "frise", subBreeds: [{ breed: "frise", subBreed: "bichon" }] },
    { breed: "germanshepherd", subBreeds: [] },
    {
        breed: "greyhound",
        subBreeds: [{ breed: "greyhound", subBreed: "italian" }],
    },
    { breed: "groenendael", subBreeds: [] },
    {
        breed: "hound",
        subBreeds: [
            { breed: "hound", subBreed: "afghan" },
            { breed: "hound", subBreed: "basset" },
            { breed: "hound", subBreed: "blood" },
            { breed: "hound", subBreed: "english" },
            { breed: "hound", subBreed: "ibizan" },
            { breed: "hound", subBreed: "walker" },
        ],
    },
    { breed: "husky", subBreeds: [] },
    { breed: "keeshond", subBreeds: [] },
    { breed: "kelpie", subBreeds: [] },
    { breed: "komondor", subBreeds: [] },
    { breed: "kuvasz", subBreeds: [] },
    { breed: "labrador", subBreeds: [] },
    { breed: "leonberg", subBreeds: [] },
    { breed: "lhasa", subBreeds: [] },
    { breed: "malamute", subBreeds: [] },
    { breed: "malinois", subBreeds: [] },
    { breed: "maltese", subBreeds: [] },
    {
        breed: "mastiff",
        subBreeds: [
            { breed: "mastiff", subBreed: "bull" },
            { breed: "mastiff", subBreed: "english" },
            { breed: "mastiff", subBreed: "tibetan" },
        ],
    },
    { breed: "mexicanhairless", subBreeds: [] },
    { breed: "mix", subBreeds: [] },
    {
        breed: "mountain",
        subBreeds: [
            { breed: "mountain", subBreed: "bernese" },
            { breed: "mountain", subBreed: "swiss" },
        ],
    },
    { breed: "newfoundland", subBreeds: [] },
    { breed: "otterhound", subBreeds: [] },
    { breed: "papillon", subBreeds: [] },
    { breed: "pekinese", subBreeds: [] },
    { breed: "pembroke", subBreeds: [] },
    {
        breed: "pinscher",
        subBreeds: [{ breed: "pinscher", subBreed: "miniature" }],
    },
    {
        breed: "pointer",
        subBreeds: [
            { breed: "pointer", subBreed: "german" },
            { breed: "pointer", subBreed: "germanlonghair" },
        ],
    },
    { breed: "pomeranian", subBreeds: [] },
    {
        breed: "poodle",
        subBreeds: [
            { breed: "poodle", subBreed: "miniature" },
            { breed: "poodle", subBreed: "standard" },
            { breed: "poodle", subBreed: "toy" },
        ],
    },
    { breed: "pug", subBreeds: [] },
    { breed: "puggle", subBreeds: [] },
    { breed: "pyrenees", subBreeds: [] },
    { breed: "redbone", subBreeds: [] },
    {
        breed: "retriever",
        subBreeds: [
            { breed: "retriever", subBreed: "chesapeake" },
            { breed: "retriever", subBreed: "curly" },
            { breed: "retriever", subBreed: "flatcoated" },
            { breed: "retriever", subBreed: "golden" },
        ],
    },
    {
        breed: "ridgeback",
        subBreeds: [{ breed: "ridgeback", subBreed: "rhodesian" }],
    },
    { breed: "rottweiler", subBreeds: [] },
    { breed: "saluki", subBreeds: [] },
    { breed: "samoyed", subBreeds: [] },
    { breed: "schipperke", subBreeds: [] },
    {
        breed: "schnauzer",
        subBreeds: [
            { breed: "schnauzer", subBreed: "giant" },
            { breed: "schnauzer", subBreed: "miniature" },
        ],
    },
    {
        breed: "setter",
        subBreeds: [
            { breed: "setter", subBreed: "english" },
            { breed: "setter", subBreed: "gordon" },
            { breed: "setter", subBreed: "irish" },
        ],
    },
    {
        breed: "sheepdog",
        subBreeds: [
            { breed: "sheepdog", subBreed: "english" },
            { breed: "sheepdog", subBreed: "shetland" },
        ],
    },
    { breed: "shiba", subBreeds: [] },
    { breed: "shihtzu", subBreeds: [] },
    {
        breed: "spaniel",
        subBreeds: [
            { breed: "spaniel", subBreed: "blenheim" },
            { breed: "spaniel", subBreed: "brittany" },
            { breed: "spaniel", subBreed: "cocker" },
            { breed: "spaniel", subBreed: "irish" },
            { breed: "spaniel", subBreed: "japanese" },
            { breed: "spaniel", subBreed: "sussex" },
            { breed: "spaniel", subBreed: "welsh" },
        ],
    },
    {
        breed: "springer",
        subBreeds: [{ breed: "springer", subBreed: "english" }],
    },
    { breed: "stbernard", subBreeds: [] },
    {
        breed: "terrier",
        subBreeds: [
            { breed: "terrier", subBreed: "american" },
            { breed: "terrier", subBreed: "australian" },
            { breed: "terrier", subBreed: "bedlington" },
            { breed: "terrier", subBreed: "border" },
            { breed: "terrier", subBreed: "dandie" },
            { breed: "terrier", subBreed: "fox" },
            { breed: "terrier", subBreed: "irish" },
            { breed: "terrier", subBreed: "kerryblue" },
            { breed: "terrier", subBreed: "lakeland" },
            { breed: "terrier", subBreed: "norfolk" },
            { breed: "terrier", subBreed: "norwich" },
            { breed: "terrier", subBreed: "patterdale" },
            { breed: "terrier", subBreed: "russell" },
            { breed: "terrier", subBreed: "scottish" },
            { breed: "terrier", subBreed: "sealyham" },
            { breed: "terrier", subBreed: "silky" },
            { breed: "terrier", subBreed: "tibetan" },
            { breed: "terrier", subBreed: "toy" },
            { breed: "terrier", subBreed: "westhighland" },
            { breed: "terrier", subBreed: "wheaten" },
            { breed: "terrier", subBreed: "yorkshire" },
        ],
    },
    { breed: "vizsla", subBreeds: [] },
    { breed: "weimaraner", subBreeds: [] },
    { breed: "whippet", subBreeds: [] },
    {
        breed: "wolfhound",
        subBreeds: [{ breed: "wolfhound", subBreed: "irish" }],
    },
]
